"""
buyers_db.py — Structured buyer criteria database parsed from the PDF.
All 35+ buyers with deal parameters, industries, geographies, and notes.
"""

BUYERS = [
    {
        "id": "magus_abraxas",
        "name": "Magus and Abraxas",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2102",
        "deal_size_min": 5_000_000,
        "deal_size_max": 100_000_000,
        "ebitda_min": 2_000_000,
        "ebitda_max": 25_000_000,
        "industries": ["aerospace", "defense", "manufacturing"],
        "sub_industries": ["casting", "CNC machining", "metal fabrication"],
        "geographies": ["midwest"],
        "states": ["IL", "IN", "OH", "MI", "WI", "MN", "IA", "MO", "ND", "SD", "NE", "KS"],
        "notes": "All sorts of manufacturing — casting to CNC",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "entier_capital",
        "name": "Entier Capital",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2059",
        "deal_size_min": 1_000_000,
        "deal_size_max": 50_000_000,
        "ebitda_min": 300_000,
        "ebitda_max": 3_000_000,
        "industries": ["services", "financial", "hr", "it", "legal", "marketing"],
        "sub_industries": ["B2B services", "AI-led operations"],
        "geographies": ["UK"],
        "states": [],
        "notes": "UK-based services businesses where AI-led operational improvements can drive value",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "castle_pines",
        "name": "Castle Pines Capital Partners",
        "contact": "John",
        "email": "john@castlepinescapitalpartners.com",
        "phone": "(603) 689-8792",
        "url": "https://castlepinescapitalpartners.com/",
        "deal_size_min": 10_000_000,
        "deal_size_max": 50_000_000,
        "ebitda_min": 2_000_000,
        "ebitda_max": 10_000_000,
        "industries": ["services", "security", "software", "defense", "it", "transportation"],
        "sub_industries": ["niche B2B services", "software platform"],
        "geographies": ["US nationwide"],
        "states": [],
        "notes": "Niche B2B services or software platform acquisition — nationwide",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "freight_brokers_fura",
        "name": "Freight Brokers (FURA)",
        "contact": None,
        "email": "INFO@FURA.COM",
        "phone": None,
        "url": "https://fura.com/",
        "deal_size_min": 2_000_000,
        "deal_size_max": 30_000_000,
        "ebitda_min": 0,
        "ebitda_max": 5_000_000,
        "industries": ["logistics", "transportation"],
        "sub_industries": ["freight brokerage", "trucking", "3PL"],
        "geographies": ["US"],
        "states": [],
        "notes": "Logistics and transportation companies",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "everest",
        "name": "Everest",
        "contact": None,
        "email": "info@adammsp.com",
        "phone": "(415) 555-0123",
        "url": "https://www.privsource.com/seller/buyside_mandates/2077",
        "deal_size_min": 5_000_000,
        "deal_size_max": 20_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 3_000_000,
        "industries": ["general", "it"],
        "sub_industries": ["MSP", "managed services"],
        "geographies": ["US"],
        "states": [],
        "notes": "General IT businesses",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "aedn",
        "name": "AEDN",
        "contact": None,
        "email": "info@aedn.com",
        "phone": "514 389 7555",
        "url": "https://www.aedn.com/#contact",
        "deal_size_min": 2_000_000,
        "deal_size_max": 20_000_000,
        "ebitda_min": 500_000,
        "ebitda_max": 5_000_000,
        "industries": ["general", "it", "manufacturing"],
        "sub_industries": ["software VARs", "MSP", "niche B2B manufacturing", "distribution"],
        "geographies": ["US", "Canada", "Montreal", "Ottawa"],
        "states": [],
        "notes": "Tech Services (software VARs via MSP partnership) OR niche B2B manufacturing/distribution in Greater Montreal/Ottawa area. Market size <$300M.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "cicada_fund",
        "name": "Cicada Fund",
        "contact": "R.S. Morrow",
        "email": "rsmorrow@cicadafund.com",
        "phone": "310-254-0765",
        "url": "https://www.cicadafund.com/#SCHEDULEMEETING",
        "deal_size_min": 5_000_000,
        "deal_size_max": 18_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 3_000_000,
        "industries": ["general"],
        "sub_industries": [],
        "geographies": ["southeast"],
        "states": ["TX", "FL", "AR", "TN", "GA", "SC", "NC"],
        "notes": "Single acquisition. Open to nuanced deals. Wants committed leadership team, open to owner staying on. Flexible on financial criteria.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "one_acquisition",
        "name": "1 Acquisition",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://1acquisition.com/contact/",
        "deal_size_min": 2_000_000,
        "deal_size_max": 10_000_000,
        "ebitda_min": 500_000,
        "ebitda_max": 3_000_000,
        "industries": ["construction", "contracting", "home services"],
        "sub_industries": ["HVAC"],
        "geographies": ["northeast", "midwest"],
        "states": ["IL", "MD", "MN", "NJ", "NY", "DC", "PA"],
        "notes": "Construction, contracting, home services, HVAC",
        "broker": "JNS",
    },
    {
        "id": "clinical_skin",
        "name": "Clinical Skin",
        "contact": None,
        "email": "info@clinicalskin.com",
        "phone": "8883167546",
        "url": "https://clinicalskin.com/",
        "deal_size_min": 1_000_000,
        "deal_size_max": 10_000_000,
        "ebitda_min": 0,
        "ebitda_max": 1_000_000,
        "industries": ["biotech", "cosmetics", "skincare"],
        "sub_industries": ["physician-dispensed", "medspa", "DTC skincare"],
        "geographies": ["US"],
        "states": [],
        "notes": "Clinically driven science-backed skincare brands $5-10M revenue, strong formulations, defensible IP. Physician-dispensed or medspa-focused.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "black_swan",
        "name": "Black Swan Investments",
        "contact": None,
        "email": "swans@blackswanic.com",
        "phone": "1 (267) 746-1900",
        "url": "https://www.blackswanic.com/",
        "deal_size_min": 0,
        "deal_size_max": 999_999_999,
        "ebitda_min": 1_000_000,
        "ebitda_max": 7_000_000,
        "industries": ["manufacturing", "aerospace"],
        "sub_industries": ["metal fabrication", "automation", "packaging", "aerospace", "medical", "electronics"],
        "geographies": ["mid-atlantic", "northeast"],
        "states": ["PA", "NJ", "DE", "MD", "NY", "CT", "WV"],
        "notes": "Manufacturing: metal fab, automation, packaging, aerospace, medical, electronics",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "todd_ruff",
        "name": "Todd Ruff",
        "contact": "Todd Ruff",
        "email": "Toddruff2024@gmail.com",
        "phone": "5165320404",
        "url": None,
        "deal_size_min": 2_000_000,
        "deal_size_max": 15_000_000,
        "ebitda_min": 400_000,
        "ebitda_max": 3_000_000,
        "industries": ["manufacturing"],
        "sub_industries": [],
        "geographies": ["midwest", "southeast", "south"],
        "states": ["IL", "IN", "OH", "MI", "WI", "MN", "FL", "TX", "NC", "SC"],
        "notes": "Manufacturing companies",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "strategic_succession",
        "name": "Strategic Succession Capital",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://strategic-succession.com/",
        "deal_size_min": 8_000_000,
        "deal_size_max": 999_999_999,
        "ebitda_min": 1_800_000,
        "ebitda_max": 3_500_000,
        "industries": ["chemicals", "utilities", "energy", "manufacturing", "plastics"],
        "sub_industries": ["industrial services", "technical maintenance", "critical infrastructure", "specialized manufacturing"],
        "geographies": ["texas"],
        "states": ["TX"],
        "notes": "Greater Houston TX metro. Industrial, technical, or B2B product mfg/service. Stable cash flow. NOT upstream oil and gas exclusively.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "justin_mack",
        "name": "Justin Mack",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2121",
        "deal_size_min": 0,
        "deal_size_max": 99_999_999,
        "ebitda_min": 2_000_000,
        "ebitda_max": 6_000_000,
        "industries": ["chemicals"],
        "sub_industries": ["specialty chemicals", "industrial chemicals"],
        "geographies": ["US"],
        "states": [],
        "notes": "Operator-led buyout. Consistently profitable chemical sector company.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "cedar_crest",
        "name": "Cedar Crest Capital",
        "contact": None,
        "email": None,
        "phone": "(480) 612-3149",
        "url": "https://cedarcrestcap.com/",
        "deal_size_min": 5_000_000,
        "deal_size_max": 999_000_000,
        "ebitda_min": 500_000,
        "ebitda_max": 3_000_000,
        "industries": ["manufacturing", "aerospace", "healthcare", "home services"],
        "sub_industries": [],
        "geographies": ["US"],
        "states": [],
        "notes": "No major customer concentration. Stable YoY earnings. Simple business models. Repeat customers (not project-based). Founder or family-led.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "mode_growth",
        "name": "Mode Growth Partners",
        "contact": "Mick",
        "email": "mick@modegp.com",
        "phone": "+1-949-209-9657",
        "url": "https://www.modegp.com/",
        "deal_size_min": 0,
        "deal_size_max": 999_000_000,
        "ebitda_min": 1_500_000,
        "ebitda_max": 7_000_000,
        "industries": ["manufacturing", "healthcare", "home services"],
        "sub_industries": [],
        "geographies": ["west coast"],
        "states": ["CA", "OR", "WA", "WY", "CO", "NV", "NM", "MO"],
        "notes": "High recurring revenue >50%. Margins >15%. Owner ready and willing to sell. Strong management team. West Coast or national with remote workforce.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "launch_point",
        "name": "Launch Point Partners",
        "contact": "Sanjeev",
        "email": "sanjeev@launch-point.com",
        "phone": "407-230-8445",
        "url": "https://www.launch-point.com/",
        "deal_size_min": 5_000_000,
        "deal_size_max": 999_000_000,
        "ebitda_min": 500_000,
        "ebitda_max": 999_000_000,
        "industries": ["aerospace"],
        "sub_industries": ["defense", "MRO", "aviation"],
        "geographies": ["US"],
        "states": [],
        "notes": "Aerospace acquisitions",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "baruk_capital",
        "name": "Baruk Capital",
        "contact": "Joseph",
        "email": "joseph@barukcapitalgroup.com",
        "phone": "4695405031",
        "url": "https://barukcapitalgroup.com/",
        "deal_size_min": 0,
        "deal_size_max": 999_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 3_000_000,
        "industries": ["home services"],
        "sub_industries": ["HVAC", "plumbing", "electrical", "landscaping"],
        "geographies": ["texas", "florida"],
        "states": ["TX", "FL"],
        "notes": "Dallas/Fort Worth and Miami areas. Businesses at least 10 years old.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "back_9_capital",
        "name": "Back 9 Capital Group",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2058",
        "deal_size_min": 1_000_000,
        "deal_size_max": 999_999_999,
        "ebitda_min": 700_000,
        "ebitda_max": 999_999_999,
        "industries": ["services", "it", "construction", "education", "healthcare", "security"],
        "sub_industries": [],
        "geographies": ["west"],
        "states": ["NV", "AZ", "UT", "CA"],
        "notes": ">10 employees, >10 years in business, >$1M revenue, >20% margins. $2-6M purchase price. NO restaurants, franchises, heavy manufacturing, C-stores/gas stations, smoke/weed/liquor, heavy construction. SBA qualified.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "zeon_investments",
        "name": "Zeon Investments",
        "contact": None,
        "email": "intake@farmerlawpc.com",
        "phone": "(512) 894-2128",
        "url": "https://farmerlawpc.com/",
        "deal_size_min": 0,
        "deal_size_max": 9_999_999_999,
        "ebitda_min": 500_000,
        "ebitda_max": 1_500_000,
        "industries": ["services", "legal", "software", "it"],
        "sub_industries": ["immigration law", "legal support", "legal tech"],
        "geographies": ["south"],
        "states": ["TX", "FL", "TN"],
        "notes": "Legal industry or legal support. Consistent revenue without founder. Particularly interested in immigration-related. Prefers South/Texas but open to remote.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "bmnl_acquisitions",
        "name": "BMNL Acquisitions",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2125",
        "deal_size_min": 0,
        "deal_size_max": 3_000_000,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["services"],
        "sub_industries": [],
        "geographies": ["southeast florida"],
        "states": ["FL"],
        "notes": "Service business any industry. Southeast FL (Miami-Dade to Martin County). EBITDA margins >10%. Enterprise value $3M or less (possibly more with seller financing).",
        "broker": "JNS",
    },
    {
        "id": "sette_partners",
        "name": "Sette Partners",
        "contact": None,
        "email": "CONTACT@SETTE.PRO",
        "phone": "3026071205",
        "url": None,
        "deal_size_min": 500_000,
        "deal_size_max": 999_999_999,
        "ebitda_min": 150_000,
        "ebitda_max": 3_000_000,
        "industries": ["healthcare"],
        "sub_industries": ["medical practice", "dental", "home health", "behavioral health"],
        "geographies": ["US"],
        "states": [],
        "notes": "Healthcare businesses",
        "broker": "JNS",
    },
    {
        "id": "brandon_gidicsin",
        "name": "Brandon Gidicsin / Henry Cap Group",
        "contact": "Brandon Gidicsin",
        "email": "Brandon@henrycapgroup.com",
        "phone": "516-459-2775",
        "url": "https://henrycapgroup.com/",
        "deal_size_min": 0,
        "deal_size_max": 999_999_999,
        "ebitda_min": 250_000,
        "ebitda_max": 999_999_999,
        "industries": ["manufacturing"],
        "sub_industries": [],
        "geographies": ["northeast"],
        "states": ["CT"],
        "notes": "Manufacturing in Connecticut",
        "broker": "JNS",
    },
    {
        "id": "john_stroll",
        "name": "John Stroll",
        "contact": "John Stroll",
        "email": "john.stroll@gmail.com",
        "phone": "203-981-1724",
        "url": "https://www.linkedin.com/in/john-stroll-7ba90b7/",
        "deal_size_min": 0,
        "deal_size_max": 999_999_999,
        "ebitda_min": 750_000,
        "ebitda_max": 2_500_000,
        "industries": ["general"],
        "sub_industries": [],
        "geographies": ["northeast"],
        "states": ["CT", "NY"],
        "notes": "NO car washes, building/construction, software, or technology",
        "broker": "JNS",
    },
    {
        "id": "emry_capital",
        "name": "Emry Capital",
        "contact": None,
        "email": "emry@emrycapital.com",
        "phone": "561 320 3274",
        "url": "https://www.emrycapital.com/",
        "deal_size_min": 1_000_000,
        "deal_size_max": 999_999_999,
        "ebitda_min": 500_000,
        "ebitda_max": 10_000_000,
        "industries": ["general", "manufacturing", "healthcare"],
        "sub_industries": [],
        "geographies": ["US"],
        "states": [],
        "notes": "General, manufacturing, healthcare",
        "broker": "JNS",
    },
    {
        "id": "acquiredge_partners",
        "name": "AcquirEdge Partners LLC",
        "contact": "Rokon",
        "email": "rokon@acquireedgepartnersllc.com",
        "phone": None,
        "url": "https://acquireedgepartnersllc.com/contact",
        "deal_size_min": 0,
        "deal_size_max": 999_999_999,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["manufacturing", "food", "construction", "financial services", "energy"],
        "sub_industries": [],
        "geographies": ["US"],
        "states": [],
        "notes": "Mid-market: $5M-$60M revenue. Manufacturing, food, construction, financial services, energy.",
        "broker": "JNS",
    },
    {
        "id": "burda_ventures",
        "name": "Burda Ventures",
        "contact": None,
        "email": "investments@burda.com",
        "phone": "49 89 9250 1280",
        "url": "https://www.burdaventures.com/",
        "deal_size_min": 0,
        "deal_size_max": 999_999_999,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["manufacturing", "defense", "fintech"],
        "sub_industries": ["robotics", "deeptech", "B2B fintech", "consumer fintech"],
        "geographies": ["US"],
        "states": [],
        "notes": "DeepTech (Manufacturing, Robotics, Defense) and Fintech. Debt/equity capital, M&A, deal sourcing.",
        "broker": "JNS",
    },
    {
        "id": "david_shelton",
        "name": "David Shelton",
        "contact": "David Shelton",
        "email": "dshelton@savannahservicesgroup.com",
        "phone": "8282792857",
        "url": "https://www.linkedin.com/in/dsheltontherecruiter/",
        "deal_size_min": 2_000_000,
        "deal_size_max": 999_000_000,
        "ebitda_min": 400_000,
        "ebitda_max": 999_000_000,
        "industries": ["other"],
        "sub_industries": [],
        "geographies": ["southeast"],
        "states": ["FL", "GA", "OK", "AL", "AR", "TX", "TN"],
        "notes": "Southeast US businesses",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "neul_capital",
        "name": "Neul Capital Holdings",
        "contact": None,
        "email": None,
        "phone": "402.778.4886",
        "url": "https://neulcapitalholdings.com/contact",
        "deal_size_min": 2_000_000,
        "deal_size_max": 6_000_000,
        "ebitda_min": 500_000,
        "ebitda_max": 4_000_000,
        "industries": ["financial services", "it", "software"],
        "sub_industries": [],
        "geographies": ["US", "Canada"],
        "states": [],
        "notes": "Financial services, IT, software platform businesses",
        "broker": "JNS",
    },
    {
        "id": "thomas_merkel",
        "name": "Thomas Merkel / Northline Consultancy",
        "contact": "Thomas Merkel",
        "email": "thomas@northlineconsultancy.com",
        "phone": "250-319-9572",
        "url": "https://northlineconsultancy.com/",
        "deal_size_min": 1_000_000,
        "deal_size_max": 20_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 10_000_000,
        "industries": ["general", "aerospace", "contracting", "manufacturing", "construction", "transportation"],
        "sub_industries": [],
        "geographies": ["US", "Canada"],
        "states": [],
        "notes": "5+ years in business, management team in place, owner seeking retirement. Owner MUST provide seller-side financing.",
        "broker": "Thomas Merkel",
    },
    {
        "id": "heidi_broom_maristella",
        "name": "Heidi Broom / Maristella",
        "contact": "Heidi Broom",
        "email": "opportunities@maristella.net",
        "phone": "(407) 603-8384",
        "url": "https://www.maristella.net",
        "deal_size_min": 1_000_000,
        "deal_size_max": 3_500_000,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["general", "biotech", "contracting", "financial services", "healthcare", "home services", "it", "manufacturing", "services", "software"],
        "sub_industries": [],
        "geographies": ["florida"],
        "states": ["FL"],
        "notes": "Open to many industries fitting their skill set. Florida-based.",
        "broker": "Heidi Broom",
    },
    {
        "id": "robert_kovar",
        "name": "Robert L. Kovar",
        "contact": "Robert Kovar",
        "email": "rkovar@gbconnections.com",
        "phone": "346-604-0840",
        "url": None,
        "deal_size_min": 40_000_000,
        "deal_size_max": 125_000_000,
        "ebitda_min": 6_000_000,
        "ebitda_max": 20_000_000,
        "industries": ["energy", "manufacturing"],
        "sub_industries": ["upstream oil and gas", "midstream", "downstream", "power generation"],
        "geographies": ["US", "Canada"],
        "states": [],
        "notes": "Companies designing, manufacturing, and selling products into fossil energy space (upstream, midstream, downstream, power gen). Prefer 70%+ product sales revenue.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "gautier_michenaud",
        "name": "Gautier Michenaud",
        "contact": "Gautier Michenaud",
        "email": "Acquisitions.gautiermichenaud@gmail.com",
        "phone": "+33661660795",
        "url": None,
        "deal_size_min": 2_000_000,
        "deal_size_max": 50_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 25_000_000,
        "industries": ["media", "software", "it"],
        "sub_industries": ["SEO websites", "affiliate", "content sites", "SaaS", "directories", "membership sites"],
        "geographies": ["US", "UK", "Canada", "Australia", "Europe"],
        "states": [],
        "notes": "SEO-driven websites ONLY. Min $100K/month net profit. Off-market (not on Flippa/Empire Flippers). 80%+ SEO traffic. Evergreen niche. 3+ years old. Low maintenance. NO ecom, NO agencies, NO service businesses.",
        "broker": "Gautier Michenaud",
    },
    {
        "id": "brandon_rosenthal",
        "name": "Brandon Rosenthal / VTM Consultants",
        "contact": "Brandon Rosenthal",
        "email": "brandon@vtmconsultants.com",
        "phone": "3477150700",
        "url": "https://www.vtmconsultants.com",
        "deal_size_min": 1_500_000,
        "deal_size_max": 5_000_000,
        "ebitda_min": 400_000,
        "ebitda_max": 2_000_000,
        "industries": ["transportation"],
        "sub_industries": ["trucking", "freight", "logistics", "last mile"],
        "geographies": ["US"],
        "states": [],  # Excludes HI and AK
        "notes": "Transportation businesses. Excludes Hawaii and Alaska.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "premier_construction",
        "name": "Premier Construction",
        "contact": None,
        "email": None,
        "phone": None,
        "url": "https://www.privsource.com/seller/buyside_mandates/2047",
        "deal_size_min": 0,
        "deal_size_max": 99_999_999,
        "ebitda_min": 500_000,
        "ebitda_max": 1_000_000,
        "industries": ["construction"],
        "sub_industries": [],
        "geographies": ["northeast"],
        "states": ["ME", "NH"],
        "notes": "Construction business in Portland, ME area",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "alon_debbi",
        "name": "Alon Debbi / Argon Equity",
        "contact": "Alon Debbi",
        "email": "alon@argonequity.com",
        "phone": "(240) 274-5519",
        "url": "https://sunshineservices.com/",
        "deal_size_min": 1_000_000,
        "deal_size_max": 999_999_999,
        "ebitda_min": 250_000,
        "ebitda_max": 999_999_999,
        "industries": ["home services"],
        "sub_industries": ["HVAC", "plumbing", "electrical", "cleaning", "landscaping"],
        "geographies": ["florida"],
        "states": ["FL"],
        "notes": "Home services in North Central Florida",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "james_lawson",
        "name": "James Lawson / Angry Bear Coffee",
        "contact": "James Lawson",
        "email": "james@angrybearcoffee.com",
        "phone": "1+ (614) 371-4360",
        "url": None,
        "deal_size_min": 500_000,
        "deal_size_max": 10_000_000,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["ecommerce", "media", "software"],
        "sub_industries": ["e-commerce", "marketing agencies", "SaaS", "med spas"],
        "geographies": ["US"],
        "states": [],
        "notes": "E-Commerce, Marketing Agencies, SaaS, and Med Spas. 3X-6X EBITDA multiple.",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "kevin_moen",
        "name": "Kevin Moen",
        "contact": "Kevin Moen",
        "email": "kevinmoen1@gmail.com",
        "phone": "2535081705",
        "url": None,
        "deal_size_min": 150_000,
        "deal_size_max": 500_000,
        "ebitda_min": 0,
        "ebitda_max": 999_999_999,
        "industries": ["contracting", "construction", "services"],
        "sub_industries": ["electricians", "plumbers", "fire/water/mold remediation", "painting contractors", "moving companies"],
        "geographies": ["northwest"],
        "states": ["WA"],
        "notes": "King County, WA. Electricians, plumbers, remediation, painting, moving companies.",
        "broker": "Kevin Moen",
    },
    {
        "id": "samuel_perea",
        "name": "Samuel Perea",
        "contact": "Samuel Perea",
        "email": "svpgroupventures@gmail.com",
        "phone": "702-523-9388",
        "url": None,
        "deal_size_min": 1_000_000,
        "deal_size_max": 5_000_000,
        "ebitda_min": 400_000,
        "ebitda_max": 2_000_000,
        "industries": ["general", "home services", "real estate", "transportation"],
        "sub_industries": [],
        "geographies": ["texas"],
        "states": ["TX"],
        "notes": "Texas-based general, home services, real estate, transportation businesses",
        "broker": "Jordi Quevedo-Valls",
    },
    {
        "id": "huy_tran",
        "name": "Huy Tran",
        "contact": "Huy Tran",
        "email": "Huytran1203@gmail.com",
        "phone": "7142922082",
        "url": None,
        "deal_size_min": 3_000_000,
        "deal_size_max": 5_000_000,
        "ebitda_min": 1_000_000,
        "ebitda_max": 2_000_000,
        "industries": ["general"],
        "sub_industries": [],
        "geographies": ["southwest"],
        "states": ["CA"],
        "notes": "Southern California. Open to other states if operator in place.",
        "broker": "Jordi Quevedo-Valls",
    },
]


def get_buyer_by_id(buyer_id: str) -> dict:
    return next((b for b in BUYERS if b["id"] == buyer_id), None)


def get_buyers_by_industry(industry: str) -> list:
    return [b for b in BUYERS if industry.lower() in [i.lower() for i in b["industries"]]]


def get_buyers_by_state(state: str) -> list:
    return [b for b in BUYERS if state.upper() in b["states"] or not b["states"]]


if __name__ == "__main__":
    print(f"Total buyers loaded: {len(BUYERS)}")
    for b in BUYERS:
        print(f"  - {b['name']} | Industries: {', '.join(b['industries'])} | States: {', '.join(b['states']) if b['states'] else 'US nationwide'}")
