"""
demo_data.py — Generates realistic sample leads for each buyer to demonstrate
               exactly what the system outputs when API keys are connected.

These are illustrative examples showing the data quality, format, and message
style that Apollo + web scraping produces.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from message_generator import generate_connection_request, generate_inmail

# ── SAMPLE LEADS PER BUYER ────────────────────────────────────────────────────
# Each lead mirrors the exact schema the system outputs from Apollo/scrapers.
# Fields: same as EXPORT_COLUMNS in export_leads.py

DEMO_LEADS = {

    # ── MAGUS & ABRAXAS (Midwest Manufacturing) ──────────────────────────────
    "magus_abraxas": [
        {"company_name":"Heartland Precision CNC","industry":"manufacturing","city":"Indianapolis","state":"IN","phone":"317-482-9100","company_domain":"heartlandprecision.com","employee_count":62,"estimated_revenue":"$8.2M","founded_year":1997,"description":"CNC machining center for aerospace and automotive components. ISO 9001:2015 certified. Owner approaching retirement after 27 years.","owner_name":"Dale Kowalski","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/dale-kowalski","owner_email":"","source":"apollo","match_score":94},
        {"company_name":"Great Lakes Metal Casting","industry":"manufacturing","city":"Cleveland","state":"OH","phone":"216-554-7830","company_domain":"glmcasting.com","employee_count":48,"estimated_revenue":"$5.7M","founded_year":2001,"description":"Iron and aluminum die casting for industrial OEM clients. 80% repeat customer base.","owner_name":"Patricia Evers","owner_title":"President","owner_linkedin":"linkedin.com/in/patricia-evers-mfg","owner_email":"patricia@glmcasting.com","source":"apollo","match_score":91},
        {"company_name":"Midwest Precision Stamping","industry":"manufacturing","city":"Grand Rapids","state":"MI","phone":"616-771-4402","company_domain":"midwestprecisionstamping.com","employee_count":35,"estimated_revenue":"$4.1M","founded_year":1994,"description":"Metal stamping and fabrication for HVAC and appliance OEMs. Family-owned 30 years.","owner_name":"Tom Brennan","owner_title":"Owner","owner_linkedin":"linkedin.com/in/tom-brennan-grinds","owner_email":"","source":"yelp","match_score":88},
        {"company_name":"Illinois Tool & Die Works","industry":"manufacturing","city":"Rockford","state":"IL","phone":"815-963-2288","company_domain":"iltooldie.com","employee_count":55,"estimated_revenue":"$7.3M","founded_year":1989,"description":"Custom tooling, die making, and short-run production machining. Union shop, strong margins.","owner_name":"Frank Musil","owner_title":"Owner/Operator","owner_linkedin":"linkedin.com/in/frank-musil-tool","owner_email":"frank@iltooldie.com","source":"apollo","match_score":87},
        {"company_name":"Buckeye Fabrication Group","industry":"manufacturing","city":"Dayton","state":"OH","phone":"937-228-4410","company_domain":"buckeyefab.com","employee_count":41,"estimated_revenue":"$6.0M","founded_year":2003,"description":"Sheet metal fabrication and powder coating for defense and industrial markets. ITAR registered.","owner_name":"Steve Harrington","owner_title":"CEO","owner_linkedin":"linkedin.com/in/steve-harrington-fab","owner_email":"sharrington@buckeyefab.com","source":"apollo","match_score":93},
        {"company_name":"MinneWeld Specialty Mfg","industry":"manufacturing","city":"Minneapolis","state":"MN","phone":"612-338-9920","company_domain":"minneweld.com","employee_count":28,"estimated_revenue":"$3.2M","founded_year":2006,"description":"Precision welding and assembly for medical device and semiconductor equipment manufacturers.","owner_name":"Kari Lindstrom","owner_title":"Founder","owner_linkedin":"linkedin.com/in/kari-lindstrom-mfg","owner_email":"","source":"manta","match_score":85},
        {"company_name":"Badger State Machining","industry":"manufacturing","city":"Milwaukee","state":"WI","phone":"414-671-3340","company_domain":"badgerstatemachining.com","employee_count":33,"estimated_revenue":"$4.8M","founded_year":1999,"description":"5-axis CNC machining for oil & gas and heavy equipment industries. Long-term OEM contracts.","owner_name":"Jeff Ostrowski","owner_title":"President","owner_linkedin":"linkedin.com/in/jeff-ostrowski-cnc","owner_email":"jeff@badgerstatemachining.com","source":"apollo","match_score":89},
        {"company_name":"Gateway Industrial Coatings","industry":"manufacturing","city":"St. Louis","state":"MO","phone":"314-772-8815","company_domain":"gatewayindustrial.com","employee_count":22,"estimated_revenue":"$2.9M","founded_year":2008,"description":"Industrial painting, epoxy lining, and protective coatings for manufacturing and infrastructure. Owner ready to retire.","owner_name":"Dave Molitor","owner_title":"Owner","owner_linkedin":"linkedin.com/in/dave-molitor-coatings","owner_email":"dave@gatewayindustrial.com","source":"yelp","match_score":82},
        {"company_name":"Hawkeye Hydraulics & Pneumatics","industry":"manufacturing","city":"Cedar Rapids","state":"IA","phone":"319-366-7780","company_domain":"hawkeyehydraulics.com","employee_count":19,"estimated_revenue":"$2.4M","founded_year":2010,"description":"Hydraulic cylinder manufacturing and repair for agriculture and construction equipment.","owner_name":"Mike Taber","owner_title":"Owner","owner_linkedin":"linkedin.com/in/mike-taber-hydraulics","owner_email":"mike@hawkeyehydraulics.com","source":"yellow_pages","match_score":80},
        {"company_name":"Prairie Wind Precision","industry":"manufacturing","city":"Wichita","state":"KS","phone":"316-265-4490","company_domain":"prairiewindprecision.com","employee_count":44,"estimated_revenue":"$5.5M","founded_year":1995,"description":"Aerospace-grade precision machining for Cessna, Spirit, and Beechcraft supply chain. NADCAP certified.","owner_name":"Larry Vogel","owner_title":"CEO & Founder","owner_linkedin":"linkedin.com/in/larry-vogel-aerospace","owner_email":"lvogel@prairiewindprecision.com","source":"apollo","match_score":96},
        {"company_name":"Hoosier Metal Specialties","industry":"manufacturing","city":"Fort Wayne","state":"IN","phone":"260-424-1177","company_domain":"hoosiermetal.com","employee_count":31,"estimated_revenue":"$3.8M","founded_year":2000,"description":"Aluminum extrusion fabrication and anodizing for electronics and industrial OEMs.","owner_name":"Ron Biggs","owner_title":"President","owner_linkedin":"linkedin.com/in/ron-biggs-hoosier","owner_email":"ron@hoosiermetal.com","source":"apollo","match_score":86},
    ],

    # ── BLACK SWAN INVESTMENTS (Mid-Atlantic Manufacturing) ───────────────────
    "black_swan": [
        {"company_name":"Penn Steel Fabricators","industry":"manufacturing","city":"Allentown","state":"PA","phone":"610-432-8870","company_domain":"pennsteelfab.com","employee_count":58,"estimated_revenue":"$9.1M","founded_year":1988,"description":"Structural steel fabrication and erection for commercial and industrial projects. AISC certified.","owner_name":"Angelo DiMeo","owner_title":"Owner","owner_linkedin":"linkedin.com/in/angelo-dimeo-steel","owner_email":"angelo@pennsteelfab.com","source":"apollo","match_score":95},
        {"company_name":"Garden State Automation","industry":"manufacturing","city":"Parsippany","state":"NJ","phone":"973-884-3300","company_domain":"gsautomation.com","employee_count":34,"estimated_revenue":"$6.2M","founded_year":2005,"description":"Custom industrial automation and robotics integration for pharma and food processing.","owner_name":"Chris Park","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/chris-park-automation","owner_email":"cpark@gsautomation.com","source":"apollo","match_score":93},
        {"company_name":"Chesapeake Packaging Solutions","industry":"manufacturing","city":"Baltimore","state":"MD","phone":"410-752-6600","company_domain":"chesapeakepack.com","employee_count":47,"estimated_revenue":"$7.8M","founded_year":1997,"description":"Custom corrugated and protective packaging design and manufacturing. $6M in repeat retail contracts.","owner_name":"Susan Whitmore","owner_title":"President","owner_linkedin":"linkedin.com/in/susan-whitmore-packaging","owner_email":"swhitmore@chesapeakepack.com","source":"apollo","match_score":91},
        {"company_name":"Keystone Electronics Assembly","industry":"manufacturing","city":"Pittsburgh","state":"PA","phone":"412-486-9210","company_domain":"keystoneelectronics.com","employee_count":39,"estimated_revenue":"$5.3M","founded_year":2001,"description":"PCB assembly and electronic manufacturing services (EMS) for defense and industrial customers.","owner_name":"Bob Yarosh","owner_title":"Owner","owner_linkedin":"linkedin.com/in/bob-yarosh-ems","owner_email":"byarosh@keystoneelectronics.com","source":"apollo","match_score":90},
        {"company_name":"Delaware Valley Metal Works","industry":"manufacturing","city":"Wilmington","state":"DE","phone":"302-654-7720","company_domain":"dvmetalworks.com","employee_count":26,"estimated_revenue":"$3.9M","founded_year":2003,"description":"Precision sheet metal fabrication for medical device manufacturers. ISO 13485 certified.","owner_name":"James Fiorentino","owner_title":"CEO","owner_linkedin":"linkedin.com/in/james-fiorentino-dvmw","owner_email":"jfiorentino@dvmetalworks.com","source":"apollo","match_score":94},
        {"company_name":"Empire State Precision","industry":"manufacturing","city":"Buffalo","state":"NY","phone":"716-855-4400","company_domain":"empireprecision.com","employee_count":52,"estimated_revenue":"$8.7M","founded_year":1993,"description":"Turning, milling, and grinding for aerospace and energy sector OEMs. AS9100 Rev D certified.","owner_name":"Paul Czerwinski","owner_title":"Owner/President","owner_linkedin":"linkedin.com/in/paul-czerwinski-machining","owner_email":"paul@empireprecision.com","source":"apollo","match_score":97},
        {"company_name":"Tri-State Fluid Power","industry":"manufacturing","city":"Hartford","state":"CT","phone":"860-525-8840","company_domain":"tristatefp.com","employee_count":23,"estimated_revenue":"$3.4M","founded_year":2007,"description":"Hydraulic and pneumatic system design, assembly, and repair for industrial clients in CT/NY/NJ.","owner_name":"Mark Salerno","owner_title":"Founder","owner_linkedin":"linkedin.com/in/mark-salerno-fluid","owner_email":"msalerno@tristatefp.com","source":"manta","match_score":84},
        {"company_name":"Mountain State Aerospace Mfg","industry":"manufacturing","city":"Charleston","state":"WV","phone":"304-346-8800","company_domain":"mstaerospace.com","employee_count":67,"estimated_revenue":"$11.2M","founded_year":1986,"description":"Aerospace structural components and assemblies for Boeing and Lockheed supply chain. NADCAP, AS9100.","owner_name":"Bill Adkins","owner_title":"CEO","owner_linkedin":"linkedin.com/in/bill-adkins-mst","owner_email":"badkins@mstaerospace.com","source":"apollo","match_score":98},
        {"company_name":"Philly Coatings & Finishing","industry":"manufacturing","city":"Philadelphia","state":"PA","phone":"215-336-2200","company_domain":"phillycoatings.com","employee_count":18,"estimated_revenue":"$2.6M","founded_year":2009,"description":"Industrial powder coating, e-coat, and anodizing services. Key supplier to 3 major furniture OEMs.","owner_name":"Tony Marciano","owner_title":"Owner","owner_linkedin":"linkedin.com/in/tony-marciano-coatings","owner_email":"tony@phillycoatings.com","source":"yelp","match_score":83},
        {"company_name":"Baltimore Weld & Fabrication","industry":"manufacturing","city":"Baltimore","state":"MD","phone":"410-633-4455","company_domain":"baltimoreweld.com","employee_count":31,"estimated_revenue":"$4.4M","founded_year":1998,"description":"Structural welding and custom fabrication for shipbuilding and marine industries.","owner_name":"Kevin O'Brien","owner_title":"President","owner_linkedin":"linkedin.com/in/kevin-obrien-welding","owner_email":"kobrien@baltimoreweld.com","source":"apollo","match_score":87},
    ],

    # ── BARUK CAPITAL (Home Services, Dallas/Miami) ───────────────────────────
    "baruk_capital": [
        {"company_name":"Lone Star HVAC Services","industry":"home services","city":"Dallas","state":"TX","phone":"214-823-5500","company_domain":"lonestarhvac.com","employee_count":32,"estimated_revenue":"$4.8M","founded_year":2008,"description":"Residential and light commercial HVAC installation, service, and maintenance. 2,200+ active maintenance contracts. Owner founded 17 years ago, open to exit.","owner_name":"Randy Flores","owner_title":"Founder & Owner","owner_linkedin":"linkedin.com/in/randy-flores-hvac","owner_email":"randy@lonestarhvac.com","source":"apollo","match_score":96},
        {"company_name":"South Florida Plumbing Pros","industry":"home services","city":"Miami","state":"FL","phone":"305-667-8800","company_domain":"southflplumbing.com","employee_count":22,"estimated_revenue":"$3.1M","founded_year":2005,"description":"Full-service residential plumbing in Miami-Dade and Broward. Recurring service agreements with 1,400+ homeowners.","owner_name":"Carlos Mendez","owner_title":"Owner","owner_linkedin":"linkedin.com/in/carlos-mendez-plumbing","owner_email":"cmendez@southflplumbing.com","source":"apollo","match_score":92},
        {"company_name":"DFW Elite Electric","industry":"home services","city":"Fort Worth","state":"TX","phone":"817-335-4422","company_domain":"dfweliteelectric.com","employee_count":18,"estimated_revenue":"$2.7M","founded_year":2010,"description":"Licensed electrical contracting for residential remodels and new construction. 12-year relationship with 3 regional homebuilders.","owner_name":"Miguel Torres","owner_title":"Owner","owner_linkedin":"linkedin.com/in/miguel-torres-electric","owner_email":"miguel@dfweliteelectric.com","source":"yelp","match_score":88},
        {"company_name":"Brickell Pest & Lawn","industry":"home services","city":"Miami","state":"FL","phone":"305-445-9980","company_domain":"brickellpestlawn.com","employee_count":29,"estimated_revenue":"$3.9M","founded_year":2000,"description":"Integrated pest control and lawn care with subscription model. 3,800 active subscribers in Miami-Dade. Owner 62, looking to sell.","owner_name":"Roberto Gutierrez","owner_title":"Founder","owner_linkedin":"linkedin.com/in/roberto-gutierrez-lawn","owner_email":"roberto@brickellpestlawn.com","source":"apollo","match_score":94},
        {"company_name":"Texas Comfort Air Systems","industry":"home services","city":"Houston","state":"TX","phone":"713-688-4450","company_domain":"texascomfortair.com","employee_count":41,"estimated_revenue":"$5.9M","founded_year":1999,"description":"Commercial and residential HVAC. 85% recurring revenue from service contracts. 3 licensed techs.","owner_name":"Phil Burton","owner_title":"President","owner_linkedin":"linkedin.com/in/phil-burton-hvac","owner_email":"pburton@texascomfortair.com","source":"apollo","match_score":91},
        {"company_name":"Suncoast Pool & Spa Service","industry":"home services","city":"Miami","state":"FL","phone":"305-931-7700","company_domain":"suncoastpoolservice.com","employee_count":16,"estimated_revenue":"$2.2M","founded_year":2012,"description":"Pool cleaning, maintenance, and repair with 800+ weekly service accounts in the Miami metro.","owner_name":"Jake Rivera","owner_title":"Owner","owner_linkedin":"linkedin.com/in/jake-rivera-pools","owner_email":"jrivera@suncoastpoolservice.com","source":"yelp","match_score":85},
        {"company_name":"North Texas Roofing Co.","industry":"home services","city":"Plano","state":"TX","phone":"972-633-8880","company_domain":"northtexasroofing.com","employee_count":27,"estimated_revenue":"$4.1M","founded_year":2007,"description":"Residential roofing with strong insurance restoration niche. 38% EBITDA margins. Owner retiring.","owner_name":"Scott Jennings","owner_title":"Owner/Founder","owner_linkedin":"linkedin.com/in/scott-jennings-roofing","owner_email":"scott@northtexasroofing.com","source":"apollo","match_score":93},
        {"company_name":"Miami Mechanical Systems","industry":"home services","city":"Doral","state":"FL","phone":"305-716-3300","company_domain":"miamimechanical.com","employee_count":35,"estimated_revenue":"$5.1M","founded_year":2004,"description":"HVAC, plumbing, and electrical bundled service for condo associations. 22 HOA contracts.","owner_name":"Alejandro Vega","owner_title":"CEO","owner_linkedin":"linkedin.com/in/alejandro-vega-mechanical","owner_email":"avega@miamimechanical.com","source":"apollo","match_score":95},
        {"company_name":"BigD Landscaping & Irrigation","industry":"home services","city":"Dallas","state":"TX","phone":"214-692-7750","company_domain":"bigdlandscaping.com","employee_count":44,"estimated_revenue":"$6.2M","founded_year":1996,"description":"Commercial and HOA landscaping with irrigation systems. $4M+ in annual contract revenue.","owner_name":"Tom Whitfield","owner_title":"President","owner_linkedin":"linkedin.com/in/tom-whitfield-landscaping","owner_email":"twhitfield@bigdlandscaping.com","source":"apollo","match_score":90},
        {"company_name":"Aqua Shield Waterproofing","industry":"home services","city":"Hollywood","state":"FL","phone":"954-922-6600","company_domain":"aquashieldwp.com","employee_count":14,"estimated_revenue":"$1.9M","founded_year":2013,"description":"Residential and commercial waterproofing services in SE Florida. Consistent 32% EBITDA margins.","owner_name":"Luis Castillo","owner_title":"Owner","owner_linkedin":"linkedin.com/in/luis-castillo-waterproofing","owner_email":"lcastillo@aquashieldwp.com","source":"manta","match_score":83},
    ],

    # ── STRATEGIC SUCCESSION CAPITAL (Houston Industrial) ────────────────────
    "strategic_succession": [
        {"company_name":"Gulf Coast Valve & Piping","industry":"manufacturing","city":"Houston","state":"TX","phone":"713-466-3300","company_domain":"gulfcoastvalve.com","employee_count":37,"estimated_revenue":"$6.8M","founded_year":1996,"description":"Valve distribution, actuation, and piping fabrication for petrochemical and industrial plants. 30+ year customer relationships.","owner_name":"Bobby Tran","owner_title":"Owner","owner_linkedin":"linkedin.com/in/bobby-tran-valve","owner_email":"bobby@gulfcoastvalve.com","source":"apollo","match_score":97},
        {"company_name":"Texas Industrial Coatings","industry":"manufacturing","city":"Pasadena","state":"TX","phone":"713-477-8800","company_domain":"txindustrialcoatings.com","employee_count":52,"estimated_revenue":"$9.2M","founded_year":1988,"description":"Protective coatings, linings, and blast/paint services for refineries, storage tanks, and plant infrastructure.","owner_name":"Earl Simmons","owner_title":"President & Founder","owner_linkedin":"linkedin.com/in/earl-simmons-coatings","owner_email":"esimmons@txindustrialcoatings.com","source":"apollo","match_score":96},
        {"company_name":"Baytown Electrical Services","industry":"manufacturing","city":"Baytown","state":"TX","phone":"281-427-6610","company_domain":"baytownelectrical.com","employee_count":43,"estimated_revenue":"$7.1M","founded_year":2001,"description":"Electrical construction and maintenance for petrochemical facilities. NEC and NFPA certified crews.","owner_name":"Larry Morales","owner_title":"Owner","owner_linkedin":"linkedin.com/in/larry-morales-electrical","owner_email":"lmorales@baytownelectrical.com","source":"apollo","match_score":93},
        {"company_name":"Houston Gasket & Sealing","industry":"chemicals","city":"Houston","state":"TX","phone":"713-923-5500","company_domain":"houstongasket.com","employee_count":21,"estimated_revenue":"$3.8M","founded_year":2004,"description":"Specialty gaskets, sealing solutions, and MRO supplies for chemical plants and refineries. 94% repeat revenue.","owner_name":"Diana Nguyen","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/diana-nguyen-gasket","owner_email":"dnguyen@houstongasket.com","source":"apollo","match_score":95},
        {"company_name":"Lone Star Pump Repair","industry":"manufacturing","city":"La Porte","state":"TX","phone":"281-470-9900","company_domain":"lonestarpump.com","employee_count":28,"estimated_revenue":"$4.4M","founded_year":1999,"description":"Industrial pump repair, remanufacturing, and installation for chemical and water treatment plants.","owner_name":"Craig Dupree","owner_title":"Owner","owner_linkedin":"linkedin.com/in/craig-dupree-pumps","owner_email":"cdupree@lonestarpump.com","source":"apollo","match_score":94},
        {"company_name":"Coastal Pipe & Tube","industry":"manufacturing","city":"Texas City","state":"TX","phone":"409-945-3300","company_domain":"coastalpipetube.com","employee_count":16,"estimated_revenue":"$2.9M","founded_year":2008,"description":"Pipe fitting, cutting, and threading for industrial turnaround and shutdown projects. Owner 58, planning 3-year exit.","owner_name":"Dave Keller","owner_title":"President","owner_linkedin":"linkedin.com/in/dave-keller-pipe","owner_email":"dkeller@coastalpipetube.com","source":"manta","match_score":88},
        {"company_name":"Harris County HVAC Industrial","industry":"manufacturing","city":"Channelview","state":"TX","phone":"713-452-8800","company_domain":"hchvaci.com","employee_count":39,"estimated_revenue":"$6.3M","founded_year":1994,"description":"Industrial HVAC and process cooling for chemical and food processing plants. Exclusively commercial clients.","owner_name":"Steve Pruitt","owner_title":"Owner/Operator","owner_linkedin":"linkedin.com/in/steve-pruitt-hvac-industrial","owner_email":"spruitt@hchvaci.com","source":"apollo","match_score":91},
        {"company_name":"Galveston Bay Scaffolding","industry":"construction","city":"Galveston","state":"TX","phone":"409-762-5500","company_domain":"galvestonbayscaffold.com","employee_count":33,"estimated_revenue":"$5.1M","founded_year":2002,"description":"Scaffold erection and safety equipment rental for industrial plant turnarounds and construction.","owner_name":"Rex Fontenot","owner_title":"Owner","owner_linkedin":"linkedin.com/in/rex-fontenot-scaffold","owner_email":"rex@galvestonbayscaffold.com","source":"yelp","match_score":86},
        {"company_name":"Precision Tank Services","industry":"chemicals","city":"Deer Park","state":"TX","phone":"281-930-4400","company_domain":"precisiontankservices.com","employee_count":24,"estimated_revenue":"$3.5M","founded_year":2006,"description":"Above-ground storage tank inspection, cleaning, and repair for chemical distributors and refineries.","owner_name":"Jim Theriot","owner_title":"Founder","owner_linkedin":"linkedin.com/in/jim-theriot-tanks","owner_email":"jtheriot@precisiontankservices.com","source":"apollo","match_score":92},
        {"company_name":"Houston Crane & Rigging","industry":"construction","city":"Humble","state":"TX","phone":"281-548-7700","company_domain":"houstoncranerigging.com","employee_count":47,"estimated_revenue":"$8.4M","founded_year":1990,"description":"Heavy lift and rigging services for industrial projects. Fleet of 8 cranes. Owner 64, retirement horizon.","owner_name":"Hank Guidry","owner_title":"Owner & President","owner_linkedin":"linkedin.com/in/hank-guidry-crane","owner_email":"hguidry@houstoncranerigging.com","source":"apollo","match_score":90},
    ],

    # ── ZEON INVESTMENTS (Legal Services, TX/FL/TN) ──────────────────────────
    "zeon_investments": [
        {"company_name":"Lone Star Immigration Law","industry":"legal","city":"Houston","state":"TX","phone":"713-880-9900","company_domain":"lonestarilaw.com","employee_count":14,"estimated_revenue":"$2.4M","founded_year":2007,"description":"Immigration law firm specializing in employment-based and family petitions. 92% recurring clients. Senior attorney considering retirement.","owner_name":"Maria Acevedo","owner_title":"Founding Partner","owner_linkedin":"linkedin.com/in/maria-acevedo-immigration","owner_email":"macevedo@lonestarilaw.com","source":"apollo","match_score":98},
        {"company_name":"Texas Business Process Outsourcing","industry":"legal","city":"Dallas","state":"TX","phone":"972-490-8800","company_domain":"txbpo.com","employee_count":22,"estimated_revenue":"$3.1M","founded_year":2010,"description":"Legal document preparation, court filing, and process serving for law firms statewide. 65% subscription revenue.","owner_name":"Alan Wright","owner_title":"CEO","owner_linkedin":"linkedin.com/in/alan-wright-legalbpo","owner_email":"awright@txbpo.com","source":"apollo","match_score":93},
        {"company_name":"Florida Legal Solutions","industry":"legal","city":"Tampa","state":"FL","phone":"813-223-7700","company_domain":"fllegalsolutions.com","employee_count":11,"estimated_revenue":"$1.8M","founded_year":2012,"description":"Virtual paralegal services and legal research for small law firms in Florida. Remote-first. 100% recurring revenue.","owner_name":"Jennifer Brooks","owner_title":"Founder","owner_linkedin":"linkedin.com/in/jennifer-brooks-paralegal","owner_email":"jbrooks@fllegalsolutions.com","source":"apollo","match_score":94},
        {"company_name":"Nashville Immigration Services","industry":"legal","city":"Nashville","state":"TN","phone":"615-244-8800","company_domain":"nashvilleimmigration.com","employee_count":9,"estimated_revenue":"$1.4M","founded_year":2013,"description":"Notary and document preparation for DACA, naturalization, and asylum applications. Owner moving abroad.","owner_name":"Ana Torres","owner_title":"Owner","owner_linkedin":"linkedin.com/in/ana-torres-immigration","owner_email":"atorres@nashvilleimmigration.com","source":"yelp","match_score":91},
        {"company_name":"Gulf Coast Legal Staffing","industry":"legal","city":"Austin","state":"TX","phone":"512-477-3300","company_domain":"gulfcoastlegalstaffing.com","employee_count":18,"estimated_revenue":"$2.7M","founded_year":2009,"description":"Attorney and paralegal placement for law firms and corporations in TX/LA/FL. Recurring retainer model.","owner_name":"Brad Simmons","owner_title":"President","owner_linkedin":"linkedin.com/in/brad-simmons-legal-staffing","owner_email":"bsimmons@gclegalstaffing.com","source":"apollo","match_score":89},
        {"company_name":"TexDoc Preparation Services","industry":"legal","city":"San Antonio","state":"TX","phone":"210-734-9900","company_domain":"texdoc.com","employee_count":7,"estimated_revenue":"$1.1M","founded_year":2014,"description":"Bilingual legal document preparation for Spanish-speaking community. Immigration, divorce, and real estate docs.","owner_name":"Rosa Cantu","owner_title":"Owner","owner_linkedin":"linkedin.com/in/rosa-cantu-legaldocs","owner_email":"rosa@texdoc.com","source":"manta","match_score":86},
        {"company_name":"E-Filing Solutions Inc.","industry":"legal","city":"Miami","state":"FL","phone":"305-448-8800","company_domain":"efilingsolutions.com","employee_count":12,"estimated_revenue":"$1.9M","founded_year":2011,"description":"Electronic court filing, service of process, and record retrieval for FL law firms. SaaS + service model.","owner_name":"Paul Estrada","owner_title":"CEO","owner_linkedin":"linkedin.com/in/paul-estrada-efiling","owner_email":"pestrada@efilingsolutions.com","source":"apollo","match_score":90},
        {"company_name":"Tennessee Title & Closing","industry":"legal","city":"Memphis","state":"TN","phone":"901-526-7700","company_domain":"tntitleclosing.com","employee_count":16,"estimated_revenue":"$2.3M","founded_year":2006,"description":"Real estate title search, settlement, and closing services for residential and commercial transactions.","owner_name":"Carol Davis","owner_title":"Owner & Managing Attorney","owner_linkedin":"linkedin.com/in/carol-davis-title","owner_email":"cdavis@tntitleclosing.com","source":"apollo","match_score":88},
        {"company_name":"Dallas Process Servers","industry":"legal","city":"Dallas","state":"TX","phone":"214-754-4400","company_domain":"dallasprocessservers.com","employee_count":8,"estimated_revenue":"$1.2M","founded_year":2015,"description":"Court process serving, skip tracing, and legal courier for 120+ active law firm clients.","owner_name":"Larry Henderson","owner_title":"Owner","owner_linkedin":"linkedin.com/in/larry-henderson-process","owner_email":"larry@dallasprocessservers.com","source":"yellow_pages","match_score":83},
        {"company_name":"Austin Legal Transcription","industry":"legal","city":"Austin","state":"TX","phone":"512-472-5500","company_domain":"austinlegaltranscription.com","employee_count":6,"estimated_revenue":"$900K","founded_year":2016,"description":"Legal transcription, deposition summaries, and medical records review for TX law firms. Fully remote.","owner_name":"Sarah Lin","owner_title":"Founder","owner_linkedin":"linkedin.com/in/sarah-lin-transcription","owner_email":"slin@austinlegaltranscription.com","source":"manta","match_score":81},
    ],

    # ── BACK 9 CAPITAL (Services/IT/Healthcare, NV/AZ/UT/CA) ─────────────────
    "back_9_capital": [
        {"company_name":"Desert Air Comfort Systems","industry":"home services","city":"Scottsdale","state":"AZ","phone":"480-946-3300","company_domain":"desertaircomfort.com","employee_count":27,"estimated_revenue":"$4.2M","founded_year":2004,"description":"Residential HVAC installation and service. 1,800+ maintenance agreements. Founded 20 years, owner seeking exit.","owner_name":"Gary Hoffman","owner_title":"Owner","owner_linkedin":"linkedin.com/in/gary-hoffman-hvac-az","owner_email":"ghoffman@desertaircomfort.com","source":"apollo","match_score":94},
        {"company_name":"Silver State IT Solutions","industry":"it","city":"Las Vegas","state":"NV","phone":"702-385-7700","company_domain":"silverstateit.com","employee_count":19,"estimated_revenue":"$3.1M","founded_year":2009,"description":"Managed IT services and cybersecurity for SMBs in Nevada. 95% recurring MRR. SBA pre-qualified.","owner_name":"Kevin Russo","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/kevin-russo-msp","owner_email":"krusso@silverstateit.com","source":"apollo","match_score":96},
        {"company_name":"Utah Facility Services","industry":"services","city":"Salt Lake City","state":"UT","phone":"801-355-8800","company_domain":"utahfacilityservices.com","employee_count":38,"estimated_revenue":"$5.8M","founded_year":1998,"description":"Commercial cleaning, janitorial, and facility management for corporate campuses and healthcare. 25+ year client base.","owner_name":"Tyler Mecham","owner_title":"President","owner_linkedin":"linkedin.com/in/tyler-mecham-facilities","owner_email":"tmecham@utahfacilityservices.com","source":"apollo","match_score":90},
        {"company_name":"SoCal Healthcare Staffing","industry":"healthcare","city":"San Diego","state":"CA","phone":"619-234-8800","company_domain":"socalstaffing.com","employee_count":32,"estimated_revenue":"$4.9M","founded_year":2008,"description":"Travel nursing and allied health staffing for San Diego hospitals and clinics. 85% placement renewal rate.","owner_name":"Lisa Chen","owner_title":"CEO","owner_linkedin":"linkedin.com/in/lisa-chen-healthcare-staffing","owner_email":"lchen@socalstaffing.com","source":"apollo","match_score":91},
        {"company_name":"Phoenix Security Group","industry":"security","city":"Phoenix","state":"AZ","phone":"602-268-9900","company_domain":"phoenixsecuritygroup.com","employee_count":44,"estimated_revenue":"$6.1M","founded_year":2002,"description":"Commercial security guard services and mobile patrol for retail and industrial clients in AZ. 12+ year client average.","owner_name":"Dave Connors","owner_title":"Owner","owner_linkedin":"linkedin.com/in/dave-connors-security","owner_email":"dconnors@phoenixsecuritygroup.com","source":"apollo","match_score":92},
        {"company_name":"Nevada Education Partners","industry":"education","city":"Henderson","state":"NV","phone":"702-568-4400","company_domain":"nevadaeducationpartners.com","employee_count":22,"estimated_revenue":"$3.4M","founded_year":2011,"description":"Vocational training and certification programs for healthcare, HVAC, and construction trades. State-licensed.","owner_name":"Rachel Moore","owner_title":"Founder","owner_linkedin":"linkedin.com/in/rachel-moore-vocational","owner_email":"rmoore@nevadaeducationpartners.com","source":"yelp","match_score":87},
        {"company_name":"Cal Coast Technology Group","industry":"it","city":"Orange","state":"CA","phone":"714-997-8800","company_domain":"calcoasttechgroup.com","employee_count":15,"estimated_revenue":"$2.8M","founded_year":2012,"description":"IT support, cloud migration, and cybersecurity for professional services firms in Orange County.","owner_name":"Jason Tran","owner_title":"President","owner_linkedin":"linkedin.com/in/jason-tran-it","owner_email":"jtran@calcoasttechgroup.com","source":"apollo","match_score":89},
        {"company_name":"Salt Lake Wound Care Centers","industry":"healthcare","city":"Provo","state":"UT","phone":"801-373-7700","company_domain":"slwoundcare.com","employee_count":29,"estimated_revenue":"$4.1M","founded_year":2007,"description":"Outpatient wound care clinics in Utah. 3 locations. Insurance-reimbursed. Owner physician semi-retired.","owner_name":"Dr. Mark Peterson","owner_title":"Founder & Medical Director","owner_linkedin":"linkedin.com/in/dr-mark-peterson-woundcare","owner_email":"mpeterson@slwoundcare.com","source":"apollo","match_score":93},
        {"company_name":"Tucson Pest Control Pros","industry":"services","city":"Tucson","state":"AZ","phone":"520-795-6600","company_domain":"tucsonpestpros.com","employee_count":16,"estimated_revenue":"$2.3M","founded_year":2006,"description":"Residential and commercial pest control with termite bonds. 2,800+ recurring accounts. Owner aging out.","owner_name":"Ed Santiago","owner_title":"Owner","owner_linkedin":"linkedin.com/in/ed-santiago-pest","owner_email":"esantiago@tucsonpestpros.com","source":"yelp","match_score":85},
        {"company_name":"Bay Area IT Managed Services","industry":"it","city":"Fremont","state":"CA","phone":"510-657-9900","company_domain":"bayareaitms.com","employee_count":24,"estimated_revenue":"$3.7M","founded_year":2010,"description":"Managed IT, VoIP, and cloud services for Bay Area SMBs. $2.5M MRR base. 98% client retention.","owner_name":"Priya Nair","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/priya-nair-msp","owner_email":"pnair@bayareaitms.com","source":"apollo","match_score":95},
    ],

    # ── CICADA FUND (Southeast General, TX/FL/TN/GA/SC/NC) ───────────────────
    "cicada_fund": [
        {"company_name":"Atlanta Commercial Cleaning","industry":"services","city":"Atlanta","state":"GA","phone":"404-875-7700","company_domain":"atlantacommercialcleaning.com","employee_count":54,"estimated_revenue":"$7.2M","founded_year":2001,"description":"Commercial janitorial and floor care for office buildings and medical facilities. 18-year client average. Owner ready to transition.","owner_name":"Marcus Washington","owner_title":"Founder","owner_linkedin":"linkedin.com/in/marcus-washington-cleaning","owner_email":"mwashington@atlantacommercialcleaning.com","source":"apollo","match_score":93},
        {"company_name":"Carolina Environmental Services","industry":"services","city":"Charlotte","state":"NC","phone":"704-372-9900","company_domain":"carolinaenvironmental.com","employee_count":38,"estimated_revenue":"$5.8M","founded_year":1997,"description":"Environmental compliance, industrial waste disposal, and remediation for manufacturing clients in the Carolinas.","owner_name":"Bill Thompson","owner_title":"President","owner_linkedin":"linkedin.com/in/bill-thompson-environmental","owner_email":"bthompson@carolinaenvironmental.com","source":"apollo","match_score":91},
        {"company_name":"Volunteer State Logistics","industry":"logistics","city":"Nashville","state":"TN","phone":"615-244-7700","company_domain":"volunteestatelog.com","employee_count":42,"estimated_revenue":"$6.4M","founded_year":2004,"description":"Regional freight brokerage with owned asset fleet covering TN, KY, and AL. 85% recurring shipper base.","owner_name":"Ed Cartwright","owner_title":"Owner & President","owner_linkedin":"linkedin.com/in/ed-cartwright-logistics","owner_email":"ecartwright@volunteestatelog.com","source":"apollo","match_score":89},
        {"company_name":"Palmetto Property Services","industry":"home services","city":"Columbia","state":"SC","phone":"803-254-8800","company_domain":"palmettoproperty.com","employee_count":31,"estimated_revenue":"$4.3M","founded_year":2006,"description":"Property maintenance, landscaping, and pressure washing for HOAs and commercial properties. $3.5M in contract revenue.","owner_name":"Brett Summers","owner_title":"Owner","owner_linkedin":"linkedin.com/in/brett-summers-property","owner_email":"bsummers@palmettoproperty.com","source":"yelp","match_score":87},
        {"company_name":"Gulf Breeze Medical Supplies","industry":"healthcare","city":"Tampa","state":"FL","phone":"813-839-7700","company_domain":"gulfbreezemedical.com","employee_count":19,"estimated_revenue":"$3.1M","founded_year":2009,"description":"Durable medical equipment distribution and home oxygen for FL homecare patients. 96% insurance-reimbursed.","owner_name":"Sandra Okafor","owner_title":"CEO","owner_linkedin":"linkedin.com/in/sandra-okafor-dme","owner_email":"sokafor@gulfbreezemedical.com","source":"apollo","match_score":90},
        {"company_name":"Texas Hill Country Funeral Services","industry":"services","city":"Austin","state":"TX","phone":"512-442-6600","company_domain":"hillcountryfuneral.com","employee_count":24,"estimated_revenue":"$3.6M","founded_year":1985,"description":"Family-owned funeral homes serving Central Texas. 3 locations. Recurring pre-need revenue. Owner 3rd generation, no successors.","owner_name":"Richard Bauer","owner_title":"Owner","owner_linkedin":"linkedin.com/in/richard-bauer-funeral","owner_email":"rbauer@hillcountryfuneral.com","source":"apollo","match_score":94},
        {"company_name":"Georgia Fleet Solutions","industry":"services","city":"Macon","state":"GA","phone":"478-743-8800","company_domain":"georgiafleet.com","employee_count":28,"estimated_revenue":"$4.1M","founded_year":2000,"description":"Commercial fleet maintenance and repair for mid-size logistics companies across GA. 95% B2B recurring revenue.","owner_name":"Tim Horton","owner_title":"Founder","owner_linkedin":"linkedin.com/in/tim-horton-fleet","owner_email":"thorton@georgiafleet.com","source":"apollo","match_score":88},
        {"company_name":"Lowcountry IT Services","industry":"it","city":"Charleston","state":"SC","phone":"843-577-9900","company_domain":"lowcountryit.com","employee_count":13,"estimated_revenue":"$2.0M","founded_year":2011,"description":"Managed IT and cybersecurity for Charleston-area businesses. Founder wants to sell and move.","owner_name":"Amanda Powell","owner_title":"Founder & CEO","owner_linkedin":"linkedin.com/in/amanda-powell-it","owner_email":"apowell@lowcountryit.com","source":"apollo","match_score":86},
        {"company_name":"Raleigh Water Treatment Co.","industry":"services","city":"Raleigh","state":"NC","phone":"919-833-7700","company_domain":"raleighwatertreatment.com","employee_count":17,"estimated_revenue":"$2.5M","founded_year":2008,"description":"Commercial water treatment, softening, and filtration services for offices, restaurants, and light industrial.","owner_name":"Jay Olsen","owner_title":"Owner","owner_linkedin":"linkedin.com/in/jay-olsen-water","owner_email":"jolsen@raleighwatertreatment.com","source":"manta","match_score":84},
        {"company_name":"Bayou State Distribution","industry":"logistics","city":"Houston","state":"TX","phone":"713-869-4400","company_domain":"bayoustate.com","employee_count":33,"estimated_revenue":"$5.0M","founded_year":2003,"description":"Last-mile delivery and regional distribution for consumer goods. 14 routes, 28 drivers. Owner aging out.","owner_name":"Greg Fontenot","owner_title":"President","owner_linkedin":"linkedin.com/in/greg-fontenot-distribution","owner_email":"gfontenot@bayoustate.com","source":"apollo","match_score":87},
    ],

}


def get_demo_leads(buyer_id: str) -> list:
    leads = DEMO_LEADS.get(buyer_id, [])
    buyer_map = {
        "magus_abraxas": {"id":"magus_abraxas","name":"Magus and Abraxas","industries":["manufacturing"],"states":["IL","IN","OH","MI","WI","MN"],"ebitda_min":2_000_000,"ebitda_max":25_000_000},
        "black_swan": {"id":"black_swan","name":"Black Swan Investments","industries":["manufacturing","aerospace"],"states":["PA","NJ","DE","MD","NY","CT","WV"],"ebitda_min":1_000_000,"ebitda_max":7_000_000},
        "baruk_capital": {"id":"baruk_capital","name":"Baruk Capital","industries":["home services"],"states":["TX","FL"],"ebitda_min":1_000_000,"ebitda_max":3_000_000},
        "strategic_succession": {"id":"strategic_succession","name":"Strategic Succession Capital","industries":["manufacturing","chemicals"],"states":["TX"],"ebitda_min":1_800_000,"ebitda_max":3_500_000},
        "zeon_investments": {"id":"zeon_investments","name":"Zeon Investments","industries":["legal"],"states":["TX","FL","TN"],"ebitda_min":500_000,"ebitda_max":1_500_000},
        "back_9_capital": {"id":"back_9_capital","name":"Back 9 Capital Group","industries":["services","it","healthcare"],"states":["NV","AZ","UT","CA"],"ebitda_min":700_000,"ebitda_max":999_999_999},
        "cicada_fund": {"id":"cicada_fund","name":"Cicada Fund","industries":["general"],"states":["TX","FL","GA","SC","NC","TN","AR"],"ebitda_min":1_000_000,"ebitda_max":3_000_000},
    }
    buyer = buyer_map.get(buyer_id, {"id":buyer_id,"name":buyer_id,"industries":[],"states":[],"ebitda_min":0,"ebitda_max":999_999_999})
    for lead in leads:
        lead["buyer_id"] = buyer["id"]
        lead["buyer_name"] = buyer["name"]
        lead["connection_request"] = generate_connection_request(lead)
        lead["inmail"] = generate_inmail(lead)
        lead["linkedin_search_url"] = f"https://www.linkedin.com/search/results/people/?keywords=%22{lead['company_name'].replace(' ','%20')}%22%20owner"
        lead["status"] = "new"
        lead["outreach_sent_date"] = ""
        lead["seller_responded"] = "No"
        lead["seller_interested"] = "Unknown"
        lead["response_notes"] = ""
        lead["next_action"] = "Send connection request"
        lead["date_added"] = "2026-02-17"
    return leads


def get_all_demo_leads() -> dict:
    return {bid: get_demo_leads(bid) for bid in DEMO_LEADS}


if __name__ == "__main__":
    for bid, leads in get_all_demo_leads().items():
        print(f"{bid}: {len(leads)} leads")
